apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name datamaker-hs.com;
            
            location / {
                proxy_pass http://django:8000;  # django는 Django 서비스의 이름
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # 정적 파일 서빙 설정 (필요한 경우)
            location /static/ {
                alias /static/;
            }
            
            location /media/ {
                alias /media/;
            }
        }
    }
